### ISSUE TITLE
org.openqa.selenium.JavascriptException: TypeError: axe.a11yCheck is not a function

### ISSUE THREAD

**Issue by rajudevjava** [dequelabs/axe-core#833]
After updating the axe-selenium-java project with axe.min.js v3.0.0 , there is error "org.openqa.selenium.JavascriptException: TypeError: axe.a11yCheck is not a function" . I am using AXE.java file from below link to run axe. 
https://github.com/dequelabs/axe-selenium-java/tree/master/src/main/java/com/deque/axe 
 Seeking help on solving this issue.

**Comment by WilcoFiers** [comment]
axe-selenium-java 2.x isn't compatible with axe-core 3.0. We are working on the 3.0 release, but do not yet have a release date for it. I'm closing this ticket and opening a separate one on the  axe-selenium-java repository.

**Comment by rajudevjava** [comment]
Great, Thank you!
