### ISSUE TITLE
build on windows fails in 4.9.0

### ISSUE THREAD

**Issue by EvilKarter** [dequelabs/axe-core#4407]
### Product

axe-core

### Product Version

4.9.0

### Latest Version

- [X] I have tested the issue with the latest version of the product

#### Expectation
A valid build/tasks/metadata-function-map.js like in version 4.8.4
```javascript
// This file is automatically generated using build/tasks/metadata-function-map.js
import abstractroleEvaluate from '../../checks/aria/abstractrole-evaluate.js';
import ariaAllowedAttrEvaluate from '../../checks/aria/aria-allowed-attr-evaluate.js';
....

const metadataFunctionMap = {
  'abstractrole-evaluate': abstractroleEvaluate,
  'accesskeys-after': accesskeysAfter,
....
``` 

#### Actual
build fails with 
Running "esbuild:core" (esbuild) task > lib/core/base/metadata-function-map.js:2:11: error: Syntax error "c"

```javascript
// This file is automatically generated using build/tasks/metadata-function-map.js
import lib\checks\visibility\hiddenContentEvaluate from '../../../lib\checks\visibility\hidden-content-evaluate.js';
import lib\checks\tables\thHasDataCellsEvaluate from '../../../lib\checks\tables\th-has-data-cells-evaluate.js';
....

const metadataFunctionMap = {
  'lib\checks\aria\abstractrole-evaluate': lib\checks\aria\abstractroleEvaluate,
  'lib\checks\aria\aria-allowed-attr-evaluate': lib\checks\aria\ariaAllowedAttrEvaluate,
....
``` 

#### How to Reproduce
Build on windows with 
```shell
npm run build -- --lang=de
``` 

#### Additional context
i think it is something with an upgraded dependency, because all buits in older versions are still working and I see nothing in the changelog that seems like an cause.

**Comment by straker** [comment]
Thanks for the issue. While I work on debugging this could I ask what version of node you're running?

**Comment by EvilKarter** [comment]
node -v
v20.8.1
